version: "3"

services:
  api-gateway:
    command: >
      sh -c "npm run staging"
  admin:
    deploy:
      x-aws-autoscaling:
        min: 2
        max: 5 #required
        cpu: 75
      resources:
        limits:
          cpus: '0.5'
          memory: 2048M
    command: >
      sh -c "npm run staging"
  customer:
    deploy:
      x-aws-autoscaling:
        min: 2
        max: 5 #required
        cpu: 75
      resources:
        limits:
          cpus: '0.5'
          memory: 2048M
    command: >
      sh -c "npm run staging"
  order:
    deploy:
      x-aws-autoscaling:
        min: 2
        max: 5 #required
        cpu: 75
      resources:
        limits:
          cpus: '0.5'
          memory: 2048M
    command: >
      sh -c "npm run staging"
  product:
    deploy:
      x-aws-autoscaling:
        min: 2
        max: 5 #required
        cpu: 75
      resources:
        limits:
          cpus: '0.5'
          memory: 2048M
    command: >
      sh -c "npm run staging"
  rider:
    deploy:
      x-aws-autoscaling:
        min: 2
        max: 5 #required
        cpu: 75
      resources:
        limits:
          cpus: '0.5'
          memory: 2048M
    command: >
      sh -c "npm run staging"
  notification:
    deploy:
      x-aws-autoscaling:
        min: 2
        max: 5 #required
        cpu: 75
      resources:
        limits:
          cpus: '0.5'
          memory: 2048M
    command: >
      sh -c "npm run staging"
